# ==========================================
# PROFIL DEV (Local)
# ==========================================

# Base de données (Création/Mise à jour automatique des tables en dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger activé en dev
springdoc.swagger-ui.enabled=true

# Logs plus détaillés pour le dev
logging.level.root=INFO
logging.level.tg.univlome.saas=DEBUG
logging.level.org.hibernate.SQL=DEBUG
