spring.application.name=saas

# ==========================================
# CONFIGURATION COMMUNE
# ==========================================
server.port=8080

# --- PostgreSQL ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/saas_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Redis ---
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:}

# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- Flyway ---
# Désactivé par défaut le temps d'avoir le premier script V1
spring.flyway.enabled=false

# --- SendGrid / Email ---
spring.sendgrid.api-key=${SENDGRID_API_KEY:}
spring.mail.default-encoding=UTF-8

# --- Swagger / OpenAPI ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=tg.univlome.saas
springdoc.paths-to-match=/**
