# ==========================================
# PROFIL DEV (Local)
# ==========================================

# --- JPA ---
# Création/Mise à jour automatique des tables (en attendant Flyway)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Swagger ---
springdoc.swagger-ui.enabled=true

# --- Logs ---
logging.level.root=INFO
logging.level.tg.univlome.saas=DEBUG
logging.level.org.hibernate.SQL=DEBUG
