spring.application.name=saas

# ==========================================
# CONFIGURATION COMMUNE
# ==========================================
server.port=8080

# Base de données PostgreSQL (valeurs via environnement ou défaut)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/saas_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# SendGrid
spring.sendgrid.api-key=${SENDGRID_API_KEY:}

# Swagger commun
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=tg.univlome.saas
springdoc.paths-to-match=/**
